### ISSUE TITLE
Declaring variables inside selectors and redefine variable inside nested media query doesn't work

### ISSUE THREAD

**Issue by judewang** [shospodarets/css-vars#1] opened 2017-04-20 10:19 UTC
Hi, I just read the post on Smashing Magazine and want to give this a try. Here's the issue I met.

```
  .cell__subtitle {
    @include css-vars(( --margin-left: r(1) ));
    display    : inline-block;
    margin-left: var(--margin-left);
    font-size  : 12px;
    @include susy($tablet) {
      display: block;
      @include css-vars(( --margin-left: 0 ));
    }
  }
```

The `margin-left: 0` didn't show in browser inspector, but when using this in native way, it worked.

**Comment by shospodarets** [comment] 2017-04-20 14:25
It's not a bug, it's one of the caveats.
Just check https://github.com/malyw/css-vars#caveats
"E.g. when you use assigned variable to define something in CSS and then reassign it- the used value will be updated. sass just inline values, so there will be no effect when you change a variable after."

Which means, till you are migrated, you have to do:
@include susy($tablet) {
      display: block;
      @include css-vars(( --margin-left: 0 ));
      margin-left: var(--margin-left);
    }

This example shows why CSS variables are more powerful than preprocessors',
as for native variables, you just change a value for a media query and browser reapplies it,
but for processors you have to provide additional CSS output.

**Closed as completed by shospodarets** 2017-04-20 14:25 UTC
